#!/bin/sh
# http://kushellig.de/neovim-php-ide/
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/../$$.tags"' EXIT
ctags -f "$dir/../$$.tags"
mv "$dir/../$$.tags" "$dir/../tags"
