#!/bin/sh

.git/hooks/ctags >/dev/null 2>&1 &

# Looks for changes and automates running bundle and other tasks.
# https://gist.github.com/stefansundin/82051ad2c8565999b914

function changed {
  git diff --name-only HEAD@{2} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'yarn.lock'; then
  echo "[yarn.lock] changed: Installing yarn dependencies..."
  yarn
fi

if changed 'composer.lock'; then
  echo "[composer.lock] changed: Installing composer dependencies..."
  composer install
fi
