#!/bin/sh

.git/hooks/ctags >/dev/null 2>&1 &

# Looks for changes and automates running bundle and other tasks.
# Does not run if your local branch is behind the remote.
# https://gist.github.com/stefansundin/82051ad2c8565999b914

# post-checkout hook - looks for changes,
# when you change branches, and if found, reinstalls the given packages every

# Exit early if this was only a file checkout, not a branch change ($3 == 1)
[[ $3 == 0 ]] && exit 0

oldRef=$1
newRef=$2

# Exit early if the local branch is behind the remote
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse @{u} 2> /dev/null)
BASE=$(git merge-base @ @{u} 2> /dev/null)

function changed {
  git diff --name-only $oldRef $newRef | grep "^$1" > /dev/null 2>&1
}

if changed 'yarn.lock'; then
  echo "[yarn.lock] changed: Installing yarn dependencies..."
  yarn
fi

if changed 'composer.lock'; then
  echo "[composer.lock] changed: Installing composer dependencies..."
  composer install
fi
