# stolen from https://github.com/gabebw/dotfiles/blob/main/rubocop.yml
AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  DisabledByDefault: true
Style/StringLiterals:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 80
