#!/bin/bash
# eval $(docker-machine env default)
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.107:2376"
export DOCKER_CERT_PATH="/Users/mikefunk/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
/usr/local/bin/docker exec -ti xsaatchi_palette_fpm_instance php $@
