#!/bin/bash
# main yadm setup file https://github.com/TheLocehiliosan/yadm
# vim: set foldmethod=marker ft=sh:

# notes {{{
# Why did I wrap everything in functions? So I could re-run specific things
# when necessary without having to re-run the entire bootstrap file. It also
# makes it easier to temporarily run one or more install steps.
#
# This is random but I thought I'd add my experience trying wuzz for an http
# client here https://github.com/asciimoo/wuzz . Basically it sucks right now.
# There's no completion for loading requests so you have to back out and load
# by file just to get another request in there. There are emacs key bindings
# but very limited vim ones. There's an error pasting a header too long for the
# tiny headers box e.g. a bearer token - it gets pasted with spaces between
# every character beyond the width of the window O_O. The only way to get that
# working is to use a saved json request (you can't load a curl request) or to
# pass in params via cli args. Without that stuff it's way worse than just
# using vim-rest-console. I also looked around for other cli http clients and
# so far no other cool ncurses clients like joplin for notes. Will keep an eye
# out for anything better or to see if wuzz gets better.
# }}}

# helper functions {{{
function log_info() { echo -e "$(tput setaf 2)$(tput rev)$(tput bold) \xE2\x9C\x93 $1 $(tput sgr0)"; "${@:2}"; }
function log_error() { echo -e "$(tput setaf 1)$(tput rev)$(tput bold) \xE2\x9C\x97 $1 $(tput sgr0)"; "${@:2}"; }
function log_notice() { echo -e "$(tput setaf 3)$(tput rev)$(tput bold) \xE2\x9A\xa0 $1 $(tput sgr0)"; "${@:2}"; }
function has() { type "$1" &>/dev/null; }
# }}}

# clone repos {{{

# log_info "Cloning repos"
# mkdir -p "$HOME/Code"
# builtin cd "$HOME/Code"
# [[ -d "$HOME/Code/mikedfunk.github.io" ]] || git clone git@github.com:mikedfunk/mikedfunk.github.io.git
# builtin cd -

# saatchi repos {{{
# mkdir -p "$HOME/Code/saatchi"
# builtin cd "$HOME/Code/saatchi"
# [[ -d "$HOME/Code/saatchi/api" ]] || git clone git@github.com:saatchiart/api.git
# [[ -d "$HOME/Code/saatchi/catalog" ]] || git clone git@github.com:saatchiart/catalog.git
# [[ -d "$HOME/Code/saatchi/couchbase-views" ]] || git clone git@github.com:saatchiart/couchbase-views.git
# [[ -d "$HOME/Code/saatchi/easel" ]] || git clone git@github.com:saatchiart/easel.git
# [[ -d "$HOME/Code/saatchi/gallery" ]] || git clone git@github.com:saatchiart/gallery.git
# [[ -d "$HOME/Code/saatchi/gitlab-puppet" ]] || git clone ab.dmdmedia.net:mike.funk/saatchi.git
# [[ -d "$HOME/Code/saatchi/imgproc" ]] || git clone git@github.com:saatchiart/imgproc.git
# [[ -d "$HOME/Code/saatchi/imgproc-python" ]] || git clone git@gitlab.dmdmedia.net:saatchiart/imgproc.git imgproc-python
# [[ -d "$HOME/Code/saatchi/maropost-php-sdk" ]] || git clone git@github.com:saatchiart/maropost-php-sdk.git
# [[ -d "$HOME/Code/saatchi/affirm-php-sdk" ]] || git clone git@github.com:saatchiart/affirm-php-sdk.git
# [[ -d "$HOME/Code/saatchi/palette" ]] || git clone git@github.com:saatchiart/palette.git
# [[ -d "$HOME/Code/saatchi/potato" ]] || git clone git@github.com:saatchiart/potato.git
# [[ -d "$HOME/Code/saatchi/saatchiart" ]] || git clone git@github.com:saatchiart/saatchiart.git legacy
# [[ -d "$HOME/Code/saatchi/xdocker" ]] || git clone git@github.com:saatchiart/xdocker.git
# [[ -d "$HOME/Code/saatchi/yzed" ]] || git clone git@github.com:saatchiart/yzed.git zed
# [[ -d "$HOME/Code/saatchi/gitlab-puppet" ]] || git clone git@gitlab.dmdmedia.net:mike.funk/saatchi.git gitlab-puppet
# [[ -d "$HOME/Code/saatchi/saatchi-kubernetes" ]] || git clone git@gitlab.dmdmedia.net:sre/saatchi-shared-libs.git saatchi-kubernetes
# builtin cd -
# }}}

# }}}

# decrypt yadm files {{{
# log_info "Decrypting yadm files"
# yadm decrypt
#
# This is commented out because it requires the GPG password each time. Yadm
# asynmetric encryption still requires a password on _decrypt_.
#
# TODO: This is also a chicken/egg scenario. Some encrypted files get symlinked
# into ~/Code/* directories, but those directories do not yet exist on a new
# install. But in order to clone those repos, I need my ssh keys, which are in
# my encrypted files too! If I decrypt _then_ clone, I'll get an error because
# the directories already exist. If I clone _then_ decrypt, I won't be able to
# clone yet.
#
# One workaround for this is to just clone the https urls for them,
# allowing me to authenticate via https basic auth. Downside: now the remotes
# on everything are set to the https version. I'll need to change to the ssh
# versions to let them use public key authorization. Hmmm...
#
# Another way would be if I was able to decrypt just my ssh keys separately.
# Maybe I can use a different encryption setup outside of yadm for those?
# Downside: now I have to deal with two methods of encryption. :(
#
# Another approach would be to decrypt, check to see if the repos have been
# cloned, if not delete the repo directories and their contents, clone, then
# decrypt again. Slight downside - I have to decrypt twice, requiring two
# password entries. But really this should only happen once - when the code has
# not been cloned. This seems like the right approach.
#
# TODO add .git/config/exclude for each codebase to yadm
# }}}

# install xcode command line tools {{{
# needed for a variety of things including phpenv (zlib), CommandLineTools below, sshpass
_install_xcode_command_line_tools () {
    log_info "Installing xcode command line tools"
    xcode-select --install || true
}
# }}}

# install necessary headers in /include on mojave {{{
# needed for phpenv and pyenv
# fyi the CommandLineTools directory doesn't even exist until you run `xcode-select --install`
# https://github.com/pyenv/pyenv/issues/1219#issuecomment-428700763
_install_necessary_headers_in_include_on_mojave () {
    if ! [ -f "/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg" ] || [ -f "$HOME/.mojave-lock" ]; then
        return
    fi
    log_info "Installing additional tools needed for mojave"
    sudo installer -pkg "/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg" -target / && touch "$HOME/.mojave-lock"
}
# }}}

# install homebrew if it's missing {{{
_install_homebrew_if_its_missing () {
    has brew && return
    log_info "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}
# }}}

# install/update homebrew packages {{{
_install_update_homebrew_packages () {
    [ -e "$HOME/.Brewfile" ] || return
    log_info "Installing/upgrading homebrew packages"
    brew update # update homebrew itself and the list of brew package versions
    brew bundle --global # install/upgrade from ~/.Brewfile
    brew upgrade         # upgrade all homebrew packages
    brew cleanup         # remove outdated versions and dead symlinks from the homebrew prefix
    # brew bundle --global cleanup --force # remove brew packages not in ~/.Brewfile
}
# }}}

# install ievms {{{
# homebrew formula is broken for this :/
_install_ievms () {
    if ! has VBoxManage; then
        log_error "VBoxManage not installed, unable to install ievms"
        return
    fi
    if ( VBoxManage list vms | grep --quiet "IE11 - Win7" ); then
        # ie11 is already installed
        return
    fi

    log_info "Installing IE11 VirtualBox VM"
    curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="11" bash
}
# }}}

# install mc {{{
_install_mc () {
    # brew formula is broken for this because it's in a private github repo :/
    has mc && return
    log_info "installing mc (memcached)"
    curl -L https://github.com/andersjanmyr/mc/releases/download/v1.4.3/mc-osx > /usr/local/bin/mc
    chmod +x /usr/local/bin/mc
}
# }}}

# akamai {{{
_install_upgrade_akamai () {
    has akamai && return
    log_info "Updating akamai commands"
    [[ "$(akamai list | grep purge)" ]] || akamai install purge
    akamai update
}
# }}}

# phpenv {{{
# I only use this because homebrew is making it difficult to install php 7.0
# and extensions right now.
#
# Update 11-16-2018: php 7.0 is still not on homebrew. I looked into asdf
# instead but the php plugin is in very shoddy condition. You have to install
# about 10 brew packages, set several env vars, and add to path before
# building. And it doesn't handle php extensions.
#
# NOTE: On mojave this won't work without `xcode-select --install` and
# installing the additional headers for libz, etc., which I do in the first few
# steps of this file
_install_upgrade_phpenv () {
    log_info "Installing/updating phpenv"
    if has phpenv; then
        # this is provided by the php-build plugin /Users/mikefunk/.phpenv/plugins/php-build/bin/phpenv-update
        # it just runs git pull in the phpenv home dir
        phpenv update
    else
        # https://github.com/phpenv/phpenv
        # https://github.com/phpenv/phpenv-installer
        curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer | bash
        # Modified version to actually support their half-assed hooks feature so I can make this work with cgr
        cp $HOME/.support/phpenv-with-hooks $(phpenv root)/libexec/phpenv
    fi
}
# }}}

# update yarn {{{
_install_upgrade_yarn () {
    log_info "Installing/upgrading yarn packages"
    builtin cd || return
    yarn global upgrade
    builtin cd - || return
}
# }}}

# set zsh as shell {{{
_set_zsh_as_shell () {
    if [[ $(grep "/usr/local/bin/zsh" /etc/shells -c) == 0 ]]; then
        log_info "Installing homebrew zsh to /etc/shells"
        sudo /bin/sh -c "echo /usr/local/bin/zsh >> /etc/shells"
    fi
    if [[ "$SHELL" != "/usr/local/bin/zsh" ]]; then
        log_info "Changing shell to homebrew zsh" chsh -s "$(which zsh)"
    fi
}
# }}}

# install legacy tmux 2.8 {{{
# this is HORRIFIC but tmux 2.9a is currently (2019-04-05) broken for me in several crucial ways:
# 1. layout `main-horizontal` will break occasionally when sprintf modified terminal output changes e.g. when text flows beyond the bottom of the pane. It crashes tmux!
# 2. <prefix>q does not show accurate data
# 3. If htop is in a right-most pane, the right side of the text will bleed over to the left side of the left-most pane by one character.
# 4. All of this happens without using tic to install tmux-256color terminfo, with an empty ~/.tmux.conf, and with an empty ~/.zshrc.
#
# tmux org seems to be aggressively removing issues and is kind of nasty in
# their responses. I think they're missing these issues because of how hostile
# they are toward any issues.
#
# TODO find minimal way to reproduce and create github issue
#
# UPDATE 2019-08-07 tmux 2.9a (latest, brew install tmux) STILL has problems:
# 1. htop sometimes bleeds vertically - the bottom pushes itself one line down into the statusbar
# 2. <prefix>q still has missing numbers
# 3. tmux occasionally crashes
_install_tmux_2_8 () {
    has tmux && return
    log_info "installing tmux 2.8"
    builtin cd || return
    wget https://github.com/tmux/tmux/releases/download/2.8/tmux-2.8.tar.gz
    tar xzvf tmux-2.8.tar.gz
    rm tmux-2.8.tar.gz
    builtin cd tmux-2.8 || return
    ./configure && make
    sudo make install
    builtin cd .. || return
    rm -rf tmux-2.8
}
# }}}

# install tmux plugin manager {{{
_install_tmux_plugin_manager () {
    [[ -d "$HOME/.tmux/plugins/tpm" ]] && return
    log_info "Installing tmux plugin manager. Upgrade packages with \`<c-a>U\`."
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
}
# }}}

# install/update tmux plugins {{{
_install_upgrade_tmux_plugins () {
    log_info "Install/upgrade tmux plugins"
    $HOME/.tmux/plugins/tpm/bin/install_plugins
    $HOME/.tmux/plugins/tpm/bin/update_plugins all
}
# }}}

# Vim {{{

# Directories {{{
_create_vim_directories () {
    if [[ ! -d "$HOME/.vim/autoload" ]]; then
        log_info "Creating required vim autoload directory"
        mkdir -p "$HOME/.vim/autoload" &&
            chmod +w "$HOME/.vim/autoload"
    fi
    if [[ ! -d "$HOME/.vim/files/info" ]]; then
        log_info "Creating required vim info directory"
        mkdir -p "$HOME/.vim/files/info" &&
            chmod a+w "$HOME/.vim/files/info"
    fi
}
# }}}

# install vim-plug {{{
_install_vim_plug () {
    [ -f $HOME/.vim/autoload/plug.vim ] && return
    log_info "Installing vim-plug"
    curl -fLo \
        ~/.vim/autoload/plug.vim \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}
# }}}

# install/upgrade vim plugins {{{
_install_upgrade_vim_plugins () {
    log_info "Installing/upgrading vim plugins"
    # vim +PlugInstall +PlugUpdate +PlugClean! +qall
    nvim +PlugUpgrade +PlugInstall +PlugUpdate +PlugClean! +UpdateRemotePlugins +qall
    # coc.nvim extension updates
    # nvim +"CocInstall coc-phpls" +CocUpdate +qall
}
# }}}

# }}}

# install node version {{{
_install_node_version () {
    local NODE_VERSION
    # NODE_VERSION="9.3.0"
    # NODE_VERSION="9.11.2"
    # NODE_VERSION="10.11.0"
    NODE_VERSION="13.2.0"
    [[ "$(nodenv version | grep $NODE_VERSION)" ]] && return
    log_info "Installing node $NODE_VERSION"
    nodenv install $NODE_VERSION && nodenv rehash && nodenv global $NODE_VERSION
}
# }}}

# configure cgr and composer {{{
_configure_cgr_and_composer () {
    local PHP_VERSION
    PHP_VERSION="$1"
    [ -z "$PHP_VERSION" ] && ( log_error "Please provide a php version"; return 1 )
    [ -d "$(phpenv root)/versions/$PHP_VERSION" ] || ( log_error "Php version ${PHP_VERSION} not found"; return 1 )
    export COMPOSER_HOME="$(phpenv root)/versions/$PHP_VERSION/composer"
    export CGR_COMPOSER_PATH="$(phpenv root)/shims/composer"
    export CGR_BASE_DIR="$(phpenv root)/versions/$PHP_VERSION/composer/global"
    export CGR_BIN_DIR="$(phpenv root)/versions/$PHP_VERSION/composer/vendor/bin"
    # export CGR_COMPOSER_PATH="$(phpenv root)/versions/${PHP_VERSION}"
}
# }}}

# install phive {{{
# NOTE: phive requires php 7.2+
_install_upgrade_phive () {
    if has phive; then
        log_info "Updating phive"
        phive selfupdate
    else
        log_info "Installing phive"
        cd
        wget -O phive.phar "https://phar.io/releases/phive.phar"
        wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
        gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
        gpg --verify phive.phar.asc phive.phar
        rm phive.phar.asc
        chmod +x phive.phar
        mv phive.phar /usr/local/bin/phive
        cd -
    fi
}
# }}}

# install php version {{{
# I only use phpenv because homebrew is making it difficult to install php 7.0
# and extensions right now.

_install_php_version () {
    export PHP_VERSION="$1" # needs exporting for the non-interactive install pear script
    ( phpenv versions | grep --quiet "$PHP_VERSION" ) && return
    log_info "Installing php $PHP_VERSION"
    # NOTE if I set php 7.1+.x to global and I use directory-specific php
    # versions and I install global composer dependencies then they will fail
    # when I have php 7.0.29 active! Same problem with rbenv, pyenv, and perlenv.
    ( phpenv versions | grep --quiet "$PHP_VERSION" ) || phpenv install "$PHP_VERSION"
    # phpenv global $PHP_VERSION
    # phpenv rehash

    # install pear so we can use pecl to install extensions
    if ! has pecl; then
        log_info "Installing pear"
        [ -f "$HOME/.bin/go-pear.phar" ] || wget -O "$HOME/.bin/go-pear.phar" http://pear.php.net/go-pear.phar
        PHP_VERSION="$PHP_VERSION" "$HOME/.support/install-pear.sh" # installs pear non-interactively
        [ -f "$HOME/.bin/go-pear.phar" ] && rm "$HOME/.bin/go-pear.phar"
    fi

    log_info "Installing additional php extensions"
    # their sdk has breaking changes all the time so I need a specific version
    yes "" | "$(phpenv root)"/versions/"$PHP_VERSION"/pear/bin/pecl install couchbase-2.2.2 && ( echo 'extension="couchbase.so"' >"$HOME/.phpenv/versions/$PHP_VERSION/etc/conf.d/couchbase.ini" )
    yes "" | "$(phpenv root)"/versions/"$PHP_VERSION"/pear/bin/pecl install memcached && ( echo 'extension="memcached.so"' >"$HOME/.phpenv/versions/$PHP_VERSION/etc/conf.d/memcached.ini" )
    yes "" | "$(phpenv root)"/versions/"$PHP_VERSION"/pear/bin/pecl install imagick && ( echo 'extension="imagick.so"' >"$HOME/.phpenv/versions/$PHP_VERSION/etc/conf.d/imagick.ini" )

    # link global composer requirements
    ln -sf "$HOME/.composer/composer.json" "$(phpenv root)/versions/$PHP_VERSION/composer/composer.json"

    # each php version has their own composer global folder
    _install_update_composer_packages "$PHP_VERSION"
}

_install_php_versions () {
    _install_php_version "7.0.29"
    _install_php_version "7.3.2"

    local PHP_VERSION
    PHP_VERSION="7.3.2"
    # PHP_VERSION="7.0.29"
    phpenv global "$PHP_VERSION"
    _configure_cgr_and_composer "$PHP_VERSION"

    phpenv rehash
}

# }}}

# install ruby version {{{
_install_ruby_version () {
    # 2.2.2 needed for catalog codebase
    if ! ( rbenv versions | grep --quiet "2.2.2" ); then
        log_info "Installing ruby 2.2.2"
        rbenv install 2.2.2 && \
            rbenv global 2.2.2 && \
            rbenv rehash && \
            gem install bundler
    fi

    # 2.5.6 needed for ios chromatic codebase
    if ! ( rbenv versions | grep --quiet "2.5.6" ); then
        log_info "Installing ruby 2.5.6"
        rbenv install 2.5.6 && \
            rbenv global 2.5.6 && \
            rbenv rehash && \
            gem install bundler
    fi

    RUBY_VERSION="2.6.5"
    ( rbenv versions | grep --quiet $RUBY_VERSION ) && return
    log_info "Installing ruby $RUBY_VERSION"
    rbenv install $RUBY_VERSION && \
        rbenv global $RUBY_VERSION && \
        rbenv rehash && \
        gem install bundler && \
        gem install rails
}
# }}}

# install perl version {{{
_install_perl_version () {
    PERL_VERSION="5.27.8"
    [[ "$(plenv version | grep $PERL_VERSION)" ]] && return
    log_info "Installing perl $PERL_VERSION"
    plenv install $PERL_VERSION && plenv rehash && plenv global $PERL_VERSION
}
# }}}

# install python3 version {{{
_install_python3_version () {
    PYTHON_INSTALL_VERSION="3.7.2"
    [[ "$(pyenv global | grep $PYTHON_INSTALL_VERSION)" ]] && return
    log_info "Installing python $PYTHON_INSTALL_VERSION"
    # CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYTHON_INSTALL_VERSION && pyenv rehash && pyenv global $PYTHON_INSTALL_VERSION
    # https://github.com/pyenv/pyenv/issues/1066#issuecomment-387211005
    pyenv install $PYTHON_INSTALL_VERSION && pyenv rehash && pyenv global $PYTHON_INSTALL_VERSION
}
# }}}

# install or upgrade ntfy {{{
# https://github.com/dschep/ntfy/issues/171#issuecomment-433388371
_install_upgrade_ntfy () {
    if has ntfy; then
        log_info "Updating ntfy"
        cd
        /usr/local/bin/python3 -m pip install --upgrade ntfy
        cd -
        return
    fi
    log_info "Installing ntfy"
    cd
    /usr/local/bin/python3 -m pip install ntfy
    cd -
}
# }}}

# install/update ruby gems {{{
# Installs from ~/Gemfile
_install_update_ruby_gems () {
    log_info "Installing/upgrading ruby gems"
    gem install bundler
    builtin cd || return
    bundle install --system --binstubs
    bundle update
    bundle clean --force
    builtin cd - || return
    has rbenv && rbenv rehash
}
# }}}

# update python3 pip packages {{{

# update all pip packages
_pip-update () {
    pip3 list --outdated | \
        grep --invert-match 'Package' | \
        grep --invert-match --regexp='\-\{5\}' | \
        awk '{print $1}' | \
        xargs -n1 pip3 install --upgrade
}
_update_python3_pip_packages () {
    log_info "Installing/upgrading pip3 packages"
    /usr/local/bin/pip3 install neovim --user # neovim uses this pip/python version
    PIP_SUCCESSFUL=1
    pip3 install -r "$HOME/requirements.txt" --user || PIP_SUCCESSFUL=0
    # pip-review broke recently:
    # zsh: /usr/local/bin/pip-review: bad interpreter: /usr/local/opt/python/bin/python3.6: no such file or directory
    # pip-review --local --auto &&
    # 	pip3 freeze >"$HOME/requirements.txt"
    # pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U
    _pip-update || PIP_SUCCESSFUL=0
    # otherwise it might freeze a failed state
    [[ $PIP_SUCCESSFUL ]] && pip3 freeze >"$HOME/requirements.txt"
    has pyenv && pyenv rehash
}
# }}}

# install/update composer and packages {{{
_install_update_composer_packages () {
    builtin cd $HOME/.composer >/dev/null || return
    # if ! has composer; then
    #     log_info "Installing composer"
    #     _install-composer
    # fi
    log_info "Installing/upgrading composer packages"

    local PHP_VERSION
    PHP_VERSION=$1
    if [ -z "$PHP_VERSION" ]; then
        PHP_VERSION=$(phpenv version | cut -d' ' -f1)
    fi

    _configure_cgr_and_composer "$PHP_VERSION"
    # use global composer.json
    [ -f "$COMPOSER_HOME/composer.json" ] || ln -sf "$HOME/.composer/composer.json" "$COMPOSER_HOME/composer.json"

    builtin cd "$(phpenv root)/versions/$PHP_VERSION/composer" >/dev/null || return

    # workaround for php language server
    mkdir -p "$(phpenv root)/versions/$PHP_VERSION/composer/global/felixfbecker/language-server/"
    ln -sf "$HOME/.composer/global/felixfbecker/language-server/composer.json" "$(phpenv root)/versions/$PHP_VERSION/composer/global/felixfbecker/language-server/composer.json"

    composer selfupdate
    composer global install
    composer global update
    if [[ ! -d "$CGR_BASE_DIR" ]]; then
        # ^ this will install cgr. Now install cgr packages...
        log_info "Installing cgr packages"
        # https://github.com/consolidation/cgr
        while read -r package; do
            cgr "$package"
        done <"$HOME/.composer/cgr-versions.txt"
    else
        log_info "Upgrading cgr packages"
        cgr update
    fi
    builtin cd - || return
    has phpenv && phpenv rehash
}
# }}}

# php-language-server {{{
_parse_php_language_server_stubs () {
    builtin cd "$HOME/.composer" || return
    log_info "Parsing php-language-server stubs"
    local PHP_VERSION
    PHP_VERSION=$(phpenv version | cut -d' ' -f1)
    composer global run-script --working-dir="$(phpenv root)/versions/$PHP_VERSION/composer/global/felixfbecker/language-server/vendor/felixfbecker/language-server" parse-stubs
    builtin cd - || return
}
# }}}

# ls_colors {{{
_install_ls_colors () {
    [ -d "$HOME"/.dircolors ] && return
    log_info "installing LS_COLORS"
    wget https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -O $HOME/.dircolors
}
# }}}

# antibody {{{
_update_antibody_plugins () {
    log_info "Updating antibody plugins"
    # source <(antibody init)
    antibody update # update all packages
}
# }}}

# apply hosts file {{{
_apply_hosts_file () {
    log_info "Syncing hosts file"
    hostess apply "$HOME/.support/hosts.json"
}
# }}}

# let iterm see italics {{{
_let_iterm_see_italics () {
    log_info "Enabling italic terminal"
    mkdir -p "$HOME/.terminfo/78"
    tic -o "$HOME/.terminfo/78/" "$HOME/.support/screen-256color.terminfo.txt"
    tic -x "$HOME/.support/tmux-256color.terminfo.txt"
}
# }}}

# Mac preferences {{{
# https://www.reddit.com/r/MacOS/comments/9ijy88/font_antialiasing_on_mojave/?utm_content=title&utm_medium=front&utm_source=reddit&utm_name=MacOS
_apply_mac_preferences () {
    defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

    # TODO write a function to abstract the repetition here
    log_info "Setting general mac preferences"
    # Disable “natural” (Lion-style) scrolling
    defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
    # dock on left side
    defaults write com.apple.dock orientation -string 'left'
    # mac dark mode
    defaults write NSGlobalDomain AppleInterfaceStyle -string 'Dark'
    # graphite color theme
    defaults write NSGlobalDomain AppleAquaColorVariant -int 6
    # disable dashboard
    defaults write com.apple.dashboard dashboard-enabled-state -int 1
    # Disable press-and-hold for keys in favor of key repeat
    # defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    # Set a blazingly fast keyboard repeat rate
    # defaults write NSGlobalDomain KeyRepeat -int 1
    # defaults write NSGlobalDomain InitialKeyRepeat -int 10
    # Increase sound quality for Bluetooth headphones/headsets
    defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
    # Require password immediately after sleep or screen saver begins
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int 0
    # Use column view in all Finder windows by default
    # Four-letter codes for the other view modes: `icnv`, `Nlsv`, `Flwv`
    defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
    # Show the ~/Library folder
    chflags nohidden ~/Library
    # Chrome - Disable the all too sensitive backswipe on Magic Mouse
    defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
    defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false

    killall Dock
    killall Finder
    killall SystemUIServer

    # finder default location home
    defaults write com.apple.finder NewWindowTargetPath "file:/$HOME/"
    if [[ $(defaults read com.apple.dock orientation) != "left" ]]; then
        log_info "Moving dock to left side"
        defaults write com.apple.dock orientation -string 'left'
        killall Dock
    fi
    if [[ $(defaults read NSGlobalDomain AppleInterfaceStyle) != "Dark" ]]; then
        log_info "Mac dark mode"
        defaults write NSGlobalDomain AppleInterfaceStyle -string 'Dark'
        killall Dock
        killall SystemUIServer
    fi
    if [[ $(defaults read NSGlobalDomain AppleAquaColorVariant) != 6 ]]; then
        log_info "Graphite color theme"
        defaults write NSGlobalDomain AppleAquaColorVariant -int 6
        killall Finder
    fi
    if [[ $(defaults read com.apple.dashboard dashboard-enabled-state) != 1 ]]; then
        log_info "Disable dashboard"
        defaults write com.apple.dashboard dashboard-enabled-state -int 1
        killall Finder
    fi
}
# }}}

# launchctl jobs {{{
# debug launchd jobs https://stackoverflow.com/q/6337513/557215
# use this form to easily generate a launchd plist: http://launched.zerowidth.com/
_start_launch_agents () {
    log_info "Starting launch agents"
    # let's use lunchy instead of launchctl! https://github.com/eddiezane/lunchy
    lunchy start --write mike.saatchi-tunnel.autossh
    lunchy start --write mike.saatchi-proxy.autossh
    # lunchy start --write mike.toaf-tunnel-prod.autossh
    # lunchy start --write mike.toaf-tunnel-qa.autossh
}
# }}}

# fix file size limit for watching with entr {{{
# http://entrproject.org/limits.html
_fix_file_size_limit_for_watching_with_entr () {
    [ -f /Library/LaunchDaemons/limit.maxfiles.plist ] && return
    log_info "Installing max files limit fixer for watching with entr"
    builtin cd /Library/LaunchDaemons || return
    sudo curl -sO http://entrproject.org/etc/limit.maxfiles.plist
    builtin cd - || return
}
# }}}

# install nix package manager {{{
_install_nix_package_manager () {
    [[ -d "/nix" ]] && return
    log_info "Installing nix package manager (will require sudo)"
    # curl https://nixos.org/nix/install | sh
    bash <(curl https://nixos.org/nix/install)
}
# }}}

# upgrade docker-machine {{{
_upgrade_docker_machine () {
    log_info "Upgrading docker-machine"
    docker-machine upgrade
}
# }}}

# link docker-for-mac {{{
_link_docker_for_mac () {
    # brew cask upgrade docker removes all docker-for-mac executables but doesn't link them, and there's no "brew cask link docker". I assume this is a temporary bug with the cask formula.
    log_info "Linking docker-for-mac binaries"
    DOCKER_APP_BIN="/Applications/Docker.app/Contents/Resources/bin"
    ln -sf "$DOCKER_APP_BIN"/docker /usr/local/bin/docker
    ln -sf "$DOCKER_APP_BIN"/docker-credential-osxkeychain /usr/local/bin/docker-credential-osxkeychain
    ln -sf "$DOCKER_APP_BIN"/docker-credential-desktop /usr/local/bin/docker-credential-desktop
    ln -sf "$DOCKER_APP_BIN"/docker-machine /usr/local/bin/docker-machine
    ln -sf "$DOCKER_APP_BIN"/docker-compose /usr/local/bin/docker-compose
}
# }}}

# reminders {{{
_show_reminders () {
    true # noop
    # log_info "Don't forget to 'docker-machine upgrade' once in a while!"
    # log_info "Don't forget to 'brew cask upgrade virtualbox virtualbox-extension-pack' once in a while!"
}
# }}}

# run functions {{{
# this way I can still source this file but comment out these function calls
# and run one or more independently. This is extremely useful!!
_install_xcode_command_line_tools
_install_necessary_headers_in_include_on_mojave
_install_homebrew_if_its_missing
_install_update_homebrew_packages
_install_ievms
_install_upgrade_akamai
_install_upgrade_phpenv
_install_upgrade_yarn
_set_zsh_as_shell
_install_tmux_2_8
_install_tmux_plugin_manager
_install_upgrade_tmux_plugins
_create_vim_directories
_install_vim_plug
_install_upgrade_vim_plugins
_install_node_version
_install_php_versions
# _install_upgrade_phive
_install_ruby_version
_install_python3_version
_install_update_ruby_gems
_update_python3_pip_packages
_install_upgrade_ntfy
_install_update_composer_packages
# _parse_php_language_server_stubs
# _install_ls_colors
_update_antibody_plugins
_apply_hosts_file
_let_iterm_see_italics
_apply_mac_preferences
_start_launch_agents
_fix_file_size_limit_for_watching_with_entr
# _upgrade_docker_machine
_link_docker_for_mac
# _install_mc
# _install_nix_package_manager
# _show_reminders
log_info "Installation complete"
# }}}
