directories:
    - application/controllers
    - 'application/modules/*/controllers'
    - application/models
    - library
    - src
    - tests

phpunit:
    binary: ./vendor/bin/phpunit
    arguments:
        --color=always
