# NOTE: there are no defaults - you can't declare part of a config. :/
# KNOWN ISSUE: If you filter then go back to all, it will run continuously. :/ You have to ctrl-c and <up><cr>

phpunit:
  # NOTE: these arguments get removed whenever a filter is applied :/
  # NOTE: yml array doesn't work here, I tried :/ damn this tool sucks!
  arguments: '--color=always -dmemory_limit=512M -ddisplay_errors=on -derror_reporting="E_ALL & ~E_NOTICE"'
watch:
  fileMask: '*.php'
  directories:
    # NOTE: this list will be trimmed if longer than about 20 lines!
    - library
    - src
    - tests
    - application/models
    - application/controllers
      # - application/modules/account
      # - application/modules/admin
    - application/modules/art
    - application/modules/art-advisory
      # - application/modules/browse
      # - application/modules/catalog
      # - application/modules/collection
      # - application/modules/curation
      # - application/modules/data
      # - application/modules/designer-rewards
      # - application/modules/ebook
      # - application/modules/feature
      # - application/modules/fulfillment
      # - application/modules/healthcheck
      # - application/modules/invest
      # - application/modules/landing
      # - application/modules/loyalty
      # - application/modules/ncr
      # - application/modules/new-sensations
      # - application/modules/newsletter
      # - application/modules/notification
      # - application/modules/shows
      # - application/modules/social
      # - application/modules/static
      # - application/modules/stripe
      # - application/modules/testimonials
      # - application/modules/theotherartfair
      # - application/modules/trending
      # - application/modules/visii
      # - application/modules/ws1
