---
repos:
  - repo: local
    hooks:
      - id: phpunit
        name: phpunit
        entry: /Users/mikefunk/.support/phpunit-pre-commit-helper.sh
        language: system
        files: ^tests\/DemandMedia\/SaatchiArt\/.*Test\.php$
      - id: php-lint
        name: php-lint
        entry: php -l
        language: system
        types: [php]
      - id: phpcs
        name: phpcs
        entry: ./vendor/bin/phpcs --standard=./phpcs.xml -s -v --colors -n
        language: system
        types: [php]
