#!/bin/sh
# God damn this path is insane
"$HOME/.phpenv/shims/php" "$HOME/.phpenv/versions/$($HOME/.phpenv/bin/phpenv version | cut -d' ' -f1)/composer/global/felixfbecker/language-server/vendor/felixfbecker/language-server/bin/php-language-server.php" --memory-limit=256M --stdio $@
