---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
        types: [json]
      - id: check-yaml
        types: [yaml]
      - id: check-xml
        types: [xml]
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: check-mailmap
  - repo: https://github.com/digitalpulp/pre-commit-php
    rev: 1.4.0
    hooks:
      - id: php-lint
        types: [php]
      - id: php-stan
        args: [--level=4, -c, phpstan.neon]
        types: [php]
  - repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
      - id: codespell
        args: [--skip="tags, vendor, .git, coverage, build"]
  - repo: local
    hooks:
      - id: phpspec
        name: phpspec
        entry: /Users/mikefunk/.support/phpspec-pre-commit-helper.sh
        language: system
        files: Spec\.php$
      - id: php-lint
        name: php-lint
        entry: php -l
        language: system
        types: [php]
      - id: phpcs
        name: phpcs
        entry: phpcs --standard=./phpcs-mike.xml -s -n -v --colors
        language: system
        types: [php]
