---
repos:
  - repo: local
    hooks:
      - id: phpspec
        name: phpspec
        entry: /Users/mikefunk/.support/phpspec-pre-commit-helper.sh
        language: system
        files: Spec\.php$
      - id: php-lint
        name: php-lint
        entry: php -l
        language: system
        types: [php]
      - id: phpcs
        name: phpcs
        entry: phpcs --standard=./phpcs-mike.xml -s -n -v --colors
        language: system
        types: [php]
